version: '2'
services:
  web:
    build: .
    command: flask run --host 0.0.0.0
    ports:
     - 5000:5000
  scheduler:
    build: .
    command: celery beat -A healthchecker.worker
    volumes:
     - out:/tmp/out
     - processed:/tmp/processed
  worker:
    build: .
    command: celery worker -A healthchecker.worker
    volumes:
     - out:/tmp/out
     - processed:/tmp/processed
  db:
    image: rethinkdb
volumes:
  out: {}
  processed: {}
